# Generated by Django 3.0.7 on 2021-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title ')),
                ('director', models.CharField(max_length=50, verbose_name='Director')),
                ('writer', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50, verbose_name='Casts')),
                ('rating', models.FloatField()),
                ('verdict', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='posters')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('recommended', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('M', 'Movie'), ('S', 'Short Film'), ('D', 'Documentry')], default='Movie', max_length=150)),
                ('certificate', models.CharField(choices=[('U', 'U'), ('U/A', 'U/A'), ('A', 'A')], default='U/A', max_length=50)),
                ('summary', models.TextField()),
                ('slug', models.SlugField()),
                ('year', models.PositiveIntegerField()),
                ('genre', models.ManyToManyField(to='store.Genre')),
            ],
            options={
                'verbose_name_plural': 'Scripts',
            },
        ),
    ]
