# Generated by Django 3.0.7 on 2021-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_script_lamguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='award_winner',
            field=models.BooleanField(default=False),
        ),
    ]
