# Generated by Django 3.0.7 on 2021-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_script_award_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.CharField(choices=[('M', 'Movie'), ('S', 'Short Film'), ('D', 'Documentry'), ('T', 'Series')], default='Movie', max_length=150),
        ),
    ]
