# Generated by Django 3.0.7 on 2021-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210421_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='cast',
            field=models.CharField(max_length=2000, verbose_name='Casts'),
        ),
        migrations.AlterField(
            model_name='script',
            name='director',
            field=models.CharField(max_length=580, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='script',
            name='writer',
            field=models.CharField(max_length=2050),
        ),
    ]
