# Generated by Django 3.0.7 on 2021-04-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210421_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='lamguage',
            new_name='language',
        ),
    ]
