# Generated by Django 3.0.7 on 2021-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210424_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_movie', models.CharField(max_length=150)),
            ],
        ),
    ]
